baseurl = "https://bloges.cortell.net/"
languageCode = "es"
title = "Blog de Jorge Cortell en castellano"
theme = "hugo-theme-casper"
disqusShortname = "jorge_cortell"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-51273041-1"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "atrévete a seguir ↓"
  cover = "https://res.cloudinary.com/jcortell/image/upload/v1578019207/Personal/cover.jpg"
  author = "Jorge Cortell"
  authorlocation = "Valencia, Europa"
  authorwebsite = "http://jorge.cortell.net"
  bio= "Fundador y Director de @kanteron, Curador de Arte"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-51273041-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "/index.xml"
  githubName = "jcortell"
  twitterName = "jorgecortell"
#  facebookName = "694855997"
  linkedinName = "jcortell"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "jorgecortell"
#    facebook = "694855997"

[[menu.main]]
  name = "Web"
  weight = -120
  identifier = "web"
  url = "https://web.cortell.net"

[[menu.main]]
  name = "Sobre mí"
  weight = -110
  identifier = "about"
  url = "https://web.cortell.net"
